Extend acceptance tests with more steps
fluxcd/terraform-provider-flux pull request #21
Opened 2020-11-02 21:40 UTC by relu

2020-11-02 22:26 UTC, phillebaba requested changes
Thanks for the awesome work! I just have one small comment before we can merge :rose:

2020-11-03 10:04 UTC, phillebaba commented on pkg/provider/data_sync_test.go
> +				Config:      `data "flux_sync" "main" {  url = "ssh://git@example.com" }`,
I think we should break these one line strings into a separate constants if they contain variables. It makes them easier to edit later on.

2020-11-03 10:48 UTC, phillebaba approved these changes
LGTM

2020-11-03 10:50 UTC, phillebaba requested changes
Sorry, it seems like when rebasing something happened to the acceptance tests. Could you fix them?

My guess is that it has to do with the fields that were removed in the docs PR.

2020-11-03 10:54 UTC, relu commented
> Sorry, it seems like when rebasing something happened to the acceptance tests. Could you fix them?
> 
> My guess is that it has to do with the fields that were removed in the docs PR.

Oops, my bad. Will push a fix.

2020-11-03 11:01 UTC, stefanprodan approved these changes
LGTM

Thanks @relu 🍰

2020-11-03 11:02 UTC, phillebaba approved these changes

2020-11-03 11:03 UTC, phillebaba commented
Great work @relu

2020-11-03 11:03 UTC, merged